### ISSUE TITLE
Ranking: show name

### ISSUE THREAD

**Issue by AlbertSuarez** [HackAssistant/registration#129]
Show only username (albert, ricard, miquel...) and no email (albert@hackupc.com, ricard@hackupc.com, miquel@hackupc...). I know that is a clear example of OCD but I think that would be more comfortable.

**Comment by casassg** [comment]
The problem is that usernames are generated automatically by extracting the first part of the email. This may be a problem in any case that people have emails under different domains and use the same user. This is the reason to keep emails instead, because that's the "original" primary key and id. The other one is auto generated and may or may not fit the email.

**Comment by AlbertSuarez** [comment]
No worries @casassg! 👍
